# Generated by Django 3.2.8 on 2022-02-20 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='employ_type',
            field=models.CharField(choices=[('정규', '정규'), ('인턴', '인턴')], max_length=20),
        ),
        migrations.CreateModel(
            name='Board_Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.AddField(
            model_name='board',
            name='board_like_user_set',
            field=models.ManyToManyField(blank=True, related_name='board_likes_user_set', through='main.Board_Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
