# Generated by Django 3.2.8 on 2022-02-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220220_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='employ_type',
            field=models.CharField(choices=[('정규', '정규'), ('인턴', '인턴')], max_length=20),
        ),
    ]
