# Generated by Django 3.2.7 on 2021-09-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_request_employ_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='employ_type',
            field=models.CharField(choices=[('인턴', '인턴'), ('IPP', 'IPP'), ('정규', '정규')], max_length=20),
        ),
    ]
