# Generated by Django 3.2.6 on 2021-10-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_request_employ_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='employ_type',
            field=models.CharField(choices=[('정규', '정규'), ('IPP', 'IPP'), ('인턴', '인턴')], max_length=20),
        ),
    ]
